services:
  mediawiki:
    image: mediawiki:1.45
    container_name: mediawiki_app
    profiles:
     - dev
     - prod
    restart: always
    ports:
      - 8080:80
    tty: true
    entrypoint:
      - "/init.sh"
    volumes:
      - mediawiki_images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./init.sh:/init.sh
      - ./setup_database.php:/tmp/setup_database.php:ro
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      WIKI_ADMIN_USER: ${WIKI_ADMIN_USER}
      WIKI_ADMIN_PASSWORD: ${WIKI_ADMIN_PASSWORD}
      WIKI_DB_APP_USER: ${WIKI_DB_APP_USER}
      WIKI_DB_APP_PASSWORD: ${WIKI_DB_APP_PASSWORD}
      WIKI_DB_SCHEMA_USER: ${WIKI_DB_SCHEMA_USER}
      WIKI_DB_SCHEMA_PASSWORD: ${WIKI_DB_SCHEMA_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  db:
    image: mariadb:11.8
    container_name: mediawiki_db
    profiles: 
     - dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  mediawiki_images:
  db_data:
